name: Made in Dublin
description: A collection of products and services crafted in Dublin.
keywords: dublin, ireland, startups, companies, tech, technology

exclude: [_less, _img, _css, _js, _icons, node_modules, s3_website.yml, package.json, README.md, GruntFile.js, Gemfile, Gemfile.lock]
safe: false
source: .
destination: ./_site

port: 3000